version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: admin
    networks:
      - mynetwork

  backend-app:
    image: backend-app
    build:
      context: .
      dockerfile: Backend.Dockerfile
    restart: always
    # corregir los puertos
    ports:
      - "5000:3001"
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  frontend-app:
    image: frontend-app
    build:
      context: .
      dockerfile: Frontend.Dockerfile
    restart: always
    # el front va en el 80
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 174.25.0.0/16