version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3310:3306
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: admin

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 174.25.0.0/16